name: Build ghidra-lx-loader
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup ghidra
        uses: er28-0652/setup-ghidra@master
        with:
          version: '11.3.2'
      - name: Build Ghidra extension (using gradle)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 'current'
          arguments: 'buildExtension'
      - uses: actions/upload-artifact@v4
        with:
          name: ghidra-lx-loader
          path: |
            dist/*.zip
